SELECT item FROM SimpleSplitFunction(CONCAT('BK_20_CDB,BK_20_CDB_SCHEMA,BK_20_MDB,BK_21_CDB,BK_21_CDB_SCHEMA,BK_21_MDB,BK_23_CDB,BK_23_CDB_SCHEMA,BK_23_MDB,BK_3_CDB,',
'BK_3_CDB_SCHEMA,BK_3_MDB,BK_6_CDB,BK_6_CDB_SCHEMA,BK_6_MDB,BK15_BK22_CDB,BK15_BK22_CDB_SCHEMA,BK15_BK22_MDB,BK15_CDB,BK15_CDB_SCHEMA,BK15_MDB,BK15_MPFM_MDB,BK16_CDB,',
'BK16_CDB_SCHEMA,BK16_MDB,BK17_CDB,BK17_CDB_SCHEMA,BK17BK8_MDB,BK19_007_CDB,BK19_007_CDB_SCHEMA,BK19_007_MDB,BK22_CDB,BK22_CDB_SCHEMA,BK22_MDB,BK4_BK4A_CDB,',
'BK4_BK4A_CDB_SCHEMA,BK4_BK4A_MDB,BK4A_ORIGINAL_CDB,BK4A_ORIGINAL_CDB_SCHEMA,BK4A_ORIGINAL_MDB,BK5_CDB,BK5_CDB_SCHEMA,BK5_MDB,BK9_MPFM_CDB,BK9_MPFM_CDB_SCHEMA,',
'BK9_MPFM_MDB,BKM_CDB,BKM_CDB_SCHEMA,BKM_MDB,BKT_CDB,BKT_CDB_SCHEMA,BKT_MDB,BKTNG_CDB,BKTNG_CDB_SCHEMA,BKTNG_MDB,CCP_CDB,CCP_CDB_SCHEMA,CCP_MDB,CPP_3_CDB,CPP_3_CDB_SCHEMA,',
'CPP_3_MDB,CPP_KNT_MDB,CPP2_CDB,CPP2_CDB_SCHEMA,CPP2_MDB,CTC1_CDB,CTC1_CDB_SCHEMA,CTC1_CTC2_CDB,CTC1_CTC2_CDB_SCHEMA,CTC1_CTC2_MDB,CTC1_MDB,GCS2_MKS_CDB,',
'GCS2_MKS_CDB_SCHEMA,GCS2_MKS_MDB,GTC1_CDB,GTC1_CDB_SCHEMA,GTC1_MDB,KNT_CPP_CDB,KNT_CPP_CDB_SCHEMA,KTN_CDB,KTN_CDB_SCHEMA,KTN_MDB,MSP_10_CDB,MSP_10_CDB_SCHEMA,',
'MSP_10_MDB,MSP9_BK18A_CDB,MSP9_BK18A_CDB_SCHEMA,MSP9_BK18A_MDB,MTC1_CDB,MTC1_CDB_SCHEMA,MTC1_MDB,NIPI2016_SDB,NIPI2016_SDB_SCHEMA,PIG_BK_2_MDB,RC1_3_CDB,',
'RC1_3_CDB_SCHEMA,RC1_3_MDB,RC10_CDB,RC10_CDB_SCHEMA,RC10_MDB,RC5RC9_CDB,RC5RC9_CDB_SCHEMA,RC6_CDB,RC6_CDB_SCHEMA,RC6_MDB,RC7_ThTC3_CDB,RC7_ThTC3_CDB_SCHEMA,',
'RC7_ThTC3_MDB,RC8_CDB,RC8_CDB_SCHEMA,RC8_MDB,RC9RC5_MDB,RP1_CDB,RP1_CDB_SCHEMA,RP1_MDB,RP2_CDB,RP2_CDB_SCHEMA,RP2_MDB,RP2_RCRB1_CDB,RP2_RCRB1_CDB_SCHEMA,',
'RP2_RCRB1_MDB,S3D_2016_DEFAULT_MODEL_MDB,STN_CDB,STN_CDB_SCHEMA,STN_MDB,STT_P2A_CDB,STT_P2A_CDB_SCHEMA,STT_P2A_MDB,ThTC1_CDB,ThTC1_CDB_SCHEMA,ThTC1_MDB,ThTC2_CDB,',
'ThTC2_CDB_SCHEMA,ThTC2_MDB,ThTC3_CDB,ThTC3_CDB_SCHEMA,ThTC3_MDB,RP3_DGCP_CDB,S3D_2016_DEFAULT_CDB,ZZADMIN_TEST_CDB,RP3_DGCP_CDB_SCHEMA,S3D_2016_DEFAULT_CDB_SCHEMA,',
'ZZADMIN_TEST_CDB_SCHEMA,RP3_DGCP_MDB,ZZADMIN_TEST_MDB'), ',')
OPEN cursorDb
FETCH NEXT FROM cursorDb INTO @DbName
WHILE @@FETCH_STATUS = 0
BEGIN
DECLARE cursorUsers CURSOR FOR
--SELECT item FROM SimpleSplitFunction('VIETSOV\duonglt.rd,VIETSOV\thanhtk.rd,VIETSOV\dieplv.rd,VIETSOV\sonpn.rd,VIETSOV\phupc.rd,VIETSOV\quangph.rd,VIETSOV\hanm.rd,VIETSOV\nguyenta.rd,VIETSOV\vinhnc.rd,VIETSOV\chungnh.rd,VIETSOV\namnq.rd,VIETSOV\nhantd.rd,VIETSOV\quochuy.pt,VIETSOV\svyatokho.rd,VIETSOV\huybt.rd,VIETSOV\huytq.rd,VIETSOV\trongvv.rd', ',')
SELECT item FROM SimpleSplitFunction(CONCAT('VIETSOV\duonglt.rd,VIETSOV\thanhtk.rd,VIETSOV\dieplv.rd,VIETSOV\sonpn.rd,VIETSOV\phupc.rd,',
'VIETSOV\quangph.rd,VIETSOV\hanm.rd,VIETSOV\nguyenta.rd,VIETSOV\vinhnc.rd,VIETSOV\chungnh.rd,VIETSOV\namnq.rd,VIETSOV\nhantd.rd,',
'VIETSOV\quochuy.pt,VIETSOV\svyatokho.rd,VIETSOV\huybt.rd,VIETSOV\huytq.rd,VIETSOV\trongvv.rd'), ',')
OPEN cursorUsers
FETCH NEXT FROM cursorUsers INTO @UserName
WHILE @@FETCH_STATUS = 0
BEGIN
set @Sql = 'Use [' + @DbName + '] IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name =''' + @UserName + ''') BEGIN CREATE USER [' + @UserName + '] FOR LOGIN [' + @UserName + '] END EXEC sp_addrolemember N''db_owner'', [' + @UserName + ']'
--exec(@sql)
--EXEC sp_addrolemember N'db_owner', @UserName
insert into #tempt(query) values (@sql)
FETCH NEXT FROM cursorUsers INTO @UserName
END
CLOSE cursorUsers
DEALLOCATE cursorUsers
FETCH NEXT FROM cursorDb INTO @DbName
END
CLOSE cursorDb
DEALLOCATE cursorDb

SELECT * FROM #tempt